development: &id1
  clients:
    default:
      database: iron_warbler_development
      hosts:
        - 127.0.0.1
development_cached: *id1
development_production:
  clients:
    default:
      database: iron_warbler_production
      hosts:
        - 127.0.0.1

test:
  clients:
    default:
      database: iron_warbler_test
      hosts:
        - 127.0.0.1

